[pytest]
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore:.*event_loop fixture.*redefined.*:DeprecationWarning

addopts =
    --cov=.
    --cov-report=term
    --cov-report=html:htmlcov
    --cov-fail-under=0
